#!/usr/bin/python3

import sys

def writePixelRow(f, pixels):
    f.write("    ")
    for i in pixels:
        f.write("0x{0:0>6x}, ".format(i))
    f.write("\n")

def writePixelFrameRows(f, frameNumber, pixels):
    f.writelines([
        "\n",
        "    // Frame {0}\n".format(frameNumber),
        "\n"
    ])

    rowSize = 10
    index = 0
    while index < len(pixels) > 0:
        writePixelRow(f, pixels[index:index + rowSize])
        index += rowSize

# setup the file name to create

fname = "frames.h"
if len(sys.argv) > 1:
    fname = sys.argv[1]

# Create the frames.h file and write the header

f = open(fname, "w")
f.writelines([
    "// Ligth-Sail frame data\n",
    "// Warning: Auto-generated by ./tools/buildFrames.py\n",
    "\n",
    "#include <pgmspace.h>\n",
    "\n",
    "const PROGMEM uint32_t frames[] = {\n"
])

# populate the frames

writePixelFrameRows(f, 1, range(1,101))
writePixelFrameRows(f, 2, range(101,201))

# Write out the footer and close the file

f.writelines([
    "};\n",
    "\n",
    "#define FRAMES_LENGTH {0}\n".format(2),
    "#define FRAMES_PIXELS {0}\n".format(100),
    "#define FRAMES_MILLIS {0:.0f}\n".format(24 / 60 * 1000)
])
f.close()