#!/usr/bin/python3

import sys
import math
import pixelUtils

def writePixelRow(f, pixels):
    f.write("    ")
    for i in pixels:
        f.write("0x{0:0>6x}, ".format(i))
    f.write("\n")

def writePixelFrameRows(f, frameNumber, pixels):
    f.writelines([
        "\n",
        "    // Frame {0}\n".format(frameNumber),
        "\n"
    ])

    rowSize = 10
    index = 0
    while index < len(pixels) > 0:
        writePixelRow(f, pixels[index:index + rowSize])
        index += rowSize

# setup the file name to create

fname = "frames.h"
if len(sys.argv) > 1:
    fname = sys.argv[1]

# Create the frames.h file and write the header

f = open(fname, "w")
f.writelines([
    "// Ligth-Sail frame data\n",
    "// Warning: Auto-generated by ./tools/buildFrames.py\n",
    "\n",
    "#include <pgmspace.h>\n",
    "\n",
    "const PROGMEM uint32_t frames[] = {\n"
])

# populate the frames

totalFrames = 0
framesPerSecond = 12
cycleSeconds = 3
framesPerCycle = framesPerSecond * cycleSeconds
pixelsPerFrame = 100

# populate rainbow first frame

frame = []
for i in range(pixelsPerFrame):
    frame.append(pixelUtils.rgb(0, 0, 0))
    
pixelsInSection = pixelsPerFrame // 7
for i in range(pixelsInSection):
    intensity = math.floor(math.sin(math.pi * (i + 1) / (pixelsInSection + 1)) * 255)
    intensity = pixelUtils.gamma8(intensity)
    frame[i + pixelsInSection * 0] = pixelUtils.rgb(0, 0, intensity)
    frame[i + pixelsInSection * 1] = pixelUtils.rgb(0, intensity, 0)
    frame[i + pixelsInSection * 2] = pixelUtils.rgb(0, intensity, intensity)
    frame[i + pixelsInSection * 3] = pixelUtils.rgb(intensity, 0, 0)
    frame[i + pixelsInSection * 4] = pixelUtils.rgb(intensity, 0, intensity)
    frame[i + pixelsInSection * 5] = pixelUtils.rgb(intensity, intensity, 0)
    frame[i + pixelsInSection * 6] = pixelUtils.rgb(intensity, intensity, intensity)

totalFrames += 1
writePixelFrameRows(f, totalFrames, frame)

# remaining frames rotate through all pixels in frame

for i in range(pixelsPerFrame - 1):
    t = frame[0]

    for j in range(pixelsPerFrame - 1):
        frame[j] = frame[j + 1]

    frame[pixelsPerFrame - 1] = t

    totalFrames += 1
    writePixelFrameRows(f, totalFrames, frame)

# Write out the footer and close the file

f.writelines([
    "};\n",
    "\n",
    "#define FRAMES_LENGTH {0}\n".format(totalFrames),
    "#define FRAMES_PIXELS {0}\n".format(pixelsPerFrame),
    "#define FRAMES_MILLIS {0:.0f}\n".format(1 / framesPerSecond * 1000)
])
f.close()