#!/usr/bin/python3

import sys
import math

def writePixelRow(f, pixels):
    f.write("    ")
    for i in pixels:
        f.write("0x{0:0>6x}, ".format(i))
    f.write("\n")

def writePixelFrameRows(f, frameNumber, pixels):
    f.writelines([
        "\n",
        "    // Frame {0}\n".format(frameNumber),
        "\n"
    ])

    rowSize = 10
    index = 0
    while index < len(pixels) > 0:
        writePixelRow(f, pixels[index:index + rowSize])
        index += rowSize

# setup the file name to create

fname = "frames.h"
if len(sys.argv) > 1:
    fname = sys.argv[1]

# Create the frames.h file and write the header

f = open(fname, "w")
f.writelines([
    "// Ligth-Sail frame data\n",
    "// Warning: Auto-generated by ./tools/buildFrames.py\n",
    "\n",
    "#include <pgmspace.h>\n",
    "\n",
    "const PROGMEM uint32_t frames[] = {\n"
])

# populate the frames

totalFrames = 0
framesPerSecond = 24
cycleSeconds = 3
framesPerCycle = framesPerSecond * cycleSeconds
pixelsPerFrame = 100

for colorCycle in range(1, 8):
    for frameInCycle in range(framesPerCycle):
        totalFrames += 1

        intensity = math.floor(math.sin(math.pi * frameInCycle / framesPerCycle) * 255)
        colorValue = 0

        if colorCycle & 1:
            colorValue |= intensity << 0

        if colorCycle & 2:
            colorValue |= intensity << 8

        if colorCycle & 4:
            colorValue |= intensity << 16

        pixels = []
        for i in range(pixelsPerFrame):
            pixels.append(colorValue)

        writePixelFrameRows(f, totalFrames, pixels)

# Write out the footer and close the file

f.writelines([
    "};\n",
    "\n",
    "#define FRAMES_LENGTH {0}\n".format(totalFrames),
    "#define FRAMES_PIXELS {0}\n".format(pixelsPerFrame),
    "#define FRAMES_MILLIS {0:.0f}\n".format(framesPerSecond / 60 * 1000)
])
f.close()